current_stage: prepare_tune
prepare_tune:
  next_stage: run_tune
  processor:
    kind: resolve_gridsearch_processor
run_tune:
  next_stage: prepare_eval
  grid:
    trainer:
      kind: finetune_trainer
    train_dataset:
      kind: vtab1k_dataset
      version: cifar
      split: train800
      transform: resize224bicubic_imagenetnorm
    eval_dataset:
      kind: vtab1k_dataset
      version: cifar
      split: val200
      transform: resize224bicubic_imagenetnorm
    model:
      kind: linear_model
    optim:
      kind: adamw
      weight_decay: 0.05
      betas: [ 0.9, 0.999 ]
      lr_scale_factor: 64
    epochs: 5
    lr: [ 5.0e-4, 1.0e-3 ]
    batch_size: 8
    schedule: warmup-cosine-10%
    precision: fp32
    seed: [ 0, 1 ]
prepare_eval:
  next_stage: run_eval
  processor:
    kind: eval_gridsearch_processor
    seeds: [ 0, 1, 2, 3, 4 ]
    train_split: train800val200
    eval_split: test
run_eval:
  next_stage: summarize
summarize:
  processor:
    kind: summarize_gridsearch_processor
    tune_stage_name: run_tune
    eval_stage_name: run_eval